version: '2'
services:
  bii1tacticalapplication-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/bii1TacticalApplication/mongodb/:/data/db/
